// Angel numbers. Each entry is authored distinctly. Angel numbers are a
// modern spiritual belief, not part of classical Pythagorean numerology;
// pages frame them as such.

export const ANGEL = {
  '000': { theme: 'infinite potential and new beginnings', meaning: 'A blank slate. Zeros amplify whatever they surround and point to a fresh cycle, a return to source, and limitless potential waiting to take shape.', seeing: 'You are at a genuine reset point — an ending has cleared space, and the field ahead is wide open.', love: 'A relationship is starting fresh or returning to its purest form; approach it with an open, unconditioned heart.' },
  '111': { theme: 'manifestation and fresh starts', meaning: 'A gateway number. One-one-one signals alignment between your thoughts and what is forming in your life — a prompt to mind what you focus on, because it is taking root.', seeing: 'Your thoughts are manifesting quickly right now; a new beginning is aligning, so aim your attention deliberately.', love: 'A new connection or a new chapter in an existing one is beginning; lead with intention.' },
  '222': { theme: 'balance, trust and partnership', meaning: 'Two-two-two is the number of harmony and faith. It asks you to trust that things are coming into balance and to keep nurturing what you have begun.', seeing: 'Stay patient and keep the faith — cooperation, balance and partnership are being restored around you.', love: 'Harmony and mutual trust are growing; keep tending the relationship gently.' },
  '333': { theme: 'expression, growth and support', meaning: 'Three-three-three carries the creative, expressive energy of Three tripled — a sign of growth, encouragement and unseen support for your self-expression.', seeing: 'You are supported and encouraged to express yourself and grow; your creative gifts want an outlet.', love: 'Communicate openly — honesty and expression will deepen the bond.' },
  '444': { theme: 'protection, stability and foundations', meaning: 'Four-four-four is a grounding, protective number. It says your foundations are solid, your effort is seen, and you are supported on the path you are building.', seeing: 'You are protected and on stable ground; keep going — the hard work you are laying down is right.', love: 'A stable, secure and honest relationship is being affirmed; build steadily.' },
  '555': { theme: 'major change and freedom', meaning: 'Five-five-five heralds significant change. It is the freedom-seeking energy of Five intensified — transformation is arriving, so loosen your grip and adapt.', seeing: 'Big change is coming or already underway; embrace it rather than resisting, freedom is on the other side.', love: 'A relationship is shifting — a new phase, or the freedom to move on; welcome the change.' },
  '666': { theme: 'rebalancing and refocusing', meaning: 'Despite its reputation, six-six-six is a gentle nudge to rebalance. It flags too much focus on worry, money or the material, and calls you back to home, care and inner life.', seeing: 'Your thoughts have tilted toward worry or the material; realign with what truly matters and care for yourself.', love: 'Refocus on nurturing and honesty rather than fear or control within the relationship.' },
  '777': { theme: 'inner wisdom and spiritual reward', meaning: 'Seven-seven-seven is the luckiest of the seeker\u2019s numbers — a sign you are aligned with your inner wisdom and that spiritual growth is bearing fruit.', seeing: 'You are on the right spiritual path; your inner work and intuition are being rewarded.', love: 'A soulful, growth-oriented connection is favoured; trust your intuition.' },
  '888': { theme: 'abundance and reward', meaning: 'Eight-eight-eight is the number of abundance and balance in the material world — effort returning as reward, and cycles of prosperity coming full circle.', seeing: 'Abundance and reward are flowing toward you; your effort is paying off, financially or otherwise.', love: 'A balanced, mutually generous relationship is favoured; give and receive equally.' },
  '999': { theme: 'completion and release', meaning: 'Nine-nine-nine marks an ending. It is the completion energy of Nine tripled — a chapter is closing so a new one can begin, and it asks you to release what is finished.', seeing: 'A significant cycle is ending; let go of what is complete to make room for what is next.', love: 'A relationship phase is concluding — either deepening into a new form or gently ending.' },
  '1010': { theme: 'alignment and awakening', meaning: 'Ten-ten pairs new beginnings with infinite potential — an awakening number that says you are aligning with your higher path and stepping into growth.', seeing: 'You are spiritually awakening and aligning with your purpose; trust the path opening ahead.', love: 'A meaningful new alignment in love; stay open to growth.' },
  '1111': { theme: 'the awakening gateway', meaning: 'The most recognised angel number. Eleven-eleven is a wake-up call and a manifestation gateway — a moment of alignment where intention and reality meet.', seeing: 'A powerful gateway is open; your thoughts are manifesting and a spiritual awakening is underway. Make a wish, and mind your focus.', love: 'A soulmate or twin-flame connection, or a profound new awareness within your relationship.' },
  '1212': { theme: 'growth and staying positive', meaning: 'Twelve-twelve blends new beginnings, partnership and higher purpose — an encouragement to keep growing, stay positive, and trust the ascent.', seeing: 'Keep rising and stay positive; you are progressing toward your purpose and out of your comfort zone.', love: 'Growth and positive momentum in a partnership; keep faith in its direction.' },
  '1221': { theme: 'balance and reflection', meaning: 'A mirror number. Twelve-twenty-one reflects your inner state back at you and asks for balance between action and trust, self and other.', seeing: 'Notice what you are projecting — the outer situation mirrors your inner one; seek balance.', love: 'Reflect on the give-and-take; harmony returns when both sides feel equal.' },
  '1234': { theme: 'steady progress in sequence', meaning: 'A step-by-step number. One-two-three-four is the sequence of orderly progress — you are moving forward one clear step at a time, exactly as you should.', seeing: 'You are making steady, sequential progress; simplify, take the next step, and trust the order of things.', love: 'The relationship is progressing naturally, one honest step at a time.' },
  '1122': { theme: 'vision and higher partnership', meaning: 'Eleven-twenty-two joins the intuitive gateway of 11 with the master-builder power of 22 — a call to turn spiritual vision into something real and lasting.', seeing: 'Align your intuition with practical action; a significant vision is ready to be built.', love: 'A destined, purpose-driven partnership; build it deliberately.' },
  '1133': { theme: 'inspired service and truth', meaning: 'Eleven-thirty-three unites intuition with the master-teacher energy of 33 — a nudge toward speaking your truth and serving others through it.', seeing: 'Share your wisdom and truth; you are being called to inspire and uplift.', love: 'Lead with compassion and honest expression.' },
  '1144': { theme: 'building on intuition', meaning: 'Eleven-forty-four grounds inspiration in solid foundations — your intuitive ideas are ready to be built into something stable.', seeing: 'Turn inspiration into disciplined action; your foundations are being blessed.', love: 'Build security on a base of honest feeling.' },
  '1155': { theme: 'liberating change', meaning: 'Eleven-fifty-five pairs awakening with major change — a fast, freeing shift that clears the way for a truer path.', seeing: 'A liberating change is arriving quickly; release the old and step forward.', love: 'A freeing shift in the relationship; welcome the new phase.' },
  '1313': { theme: 'creative transformation', meaning: 'Thirteen-thirteen blends expressive creativity with transformation — a supportive sign to grow through change and keep creating.', seeing: 'Stay optimistic through change; your creativity is carrying you upward.', love: 'Express yourself openly as the relationship transforms.' },
  '1414': { theme: 'grounded manifestation', meaning: 'Fourteen-fourteen joins fresh starts with solid structure — manifest through patient, practical effort.', seeing: 'Keep building steadily; your consistent work is manifesting real results.', love: 'Steady effort is strengthening the bond.' },
  '1515': { theme: 'positive change through choice', meaning: 'Fifteen-fifteen unites new beginnings with freedom and change — your choices are steering a positive transformation.', seeing: 'Your decisions are shaping welcome change; choose in line with your growth.', love: 'A positive shift driven by honest choices.' },
  '1616': { theme: 'harmony at home', meaning: 'Sixteen-sixteen blends new starts with the nurturing energy of Six — a call to balance ambition with home and relationships.', seeing: 'Tend to home and loved ones; realign material focus with care.', love: 'Nurture the relationship and restore harmony.' },
  '1717': { theme: 'aligned spiritual progress', meaning: 'Seventeen-seventeen joins fresh starts with the seeker\u2019s wisdom — you are progressing on an aligned spiritual path.', seeing: 'You are on the right track; your inner wisdom is guiding you well.', love: 'A soulful connection growing through shared understanding.' },
  '1818': { theme: 'abundance arriving', meaning: 'Eighteen-eighteen pairs new beginnings with the abundance of Eight — prosperity and reward are on their way.', seeing: 'Abundance is manifesting; keep your mindset positive and confident.', love: 'A balanced, prosperous phase in love.' },
  '1919': { theme: 'closing one door, opening another', meaning: 'Nineteen-nineteen joins fresh starts with completion — one chapter ends as a new, purpose-led one begins.', seeing: 'An ending is clearing the way for a meaningful new beginning; step through.', love: 'A transition into a truer chapter of the relationship.' },
  '2020': { theme: 'clarity and balanced vision', meaning: 'Twenty-twenty blends partnership with potential — a call to see clearly, cooperate, and trust the bigger plan.', seeing: 'Seek clarity and balance; cooperation and patience will reveal the way.', love: 'Clear communication restores balance.' },
  '2121': { theme: 'faith through partnership', meaning: 'Twenty-one-twenty-one joins harmony with fresh starts — keep faith as a new balanced chapter forms.', seeing: 'Trust the process; partnership and new beginnings are aligning.', love: 'Renewed faith and balance in the relationship.' },
  '2222': { theme: 'deep balance and manifestation', meaning: 'Twenty-two-twenty-two amplifies harmony and master-builder power — your patient faith is manifesting real balance.', seeing: 'Your steady faith is paying off; balance and a significant build are manifesting.', love: 'A stable, destined partnership settling into balance.' },
  '3333': { theme: 'amplified support and expression', meaning: 'Threes multiplied — a strong sign of encouragement, creative power and support surrounding your self-expression.', seeing: 'You are strongly supported; express yourself boldly and grow.', love: 'Open, joyful expression strengthens the bond.' },
  '4444': { theme: 'strong protection and foundation', meaning: 'Fours multiplied — powerful stability, protection and reassurance that your foundations are secure.', seeing: 'You are strongly protected and grounded; keep building with confidence.', love: 'A deeply secure and stable relationship is affirmed.' },
  '5555': { theme: 'sweeping transformation', meaning: 'Fives multiplied — a wave of major change and freedom; a large transformation is clearing the path.', seeing: 'A sweeping change is arriving; release control and ride the shift.', love: 'A major, freeing transformation in love.' },
  '717': { theme: 'faith on the path', meaning: 'Seven-one-seven surrounds a new start with spiritual wisdom — a reassurance that your aligned choices are blessed.', seeing: 'Have faith in your path; your spiritual choices are supported.', love: 'A growth-focused, intuitive connection.' },
  '818': { theme: 'financial and personal renewal', meaning: 'Eight-one-eight frames new beginnings with abundance — a fresh cycle of prosperity and self-belief.', seeing: 'A prosperous new cycle is opening; back yourself.', love: 'A renewed, balanced chapter in the relationship.' },
  '909': { theme: 'compassionate completion', meaning: 'Nine-zero-nine joins completion with infinite potential — a compassionate ending that opens a higher path.', seeing: 'Release what is finished with grace; a higher purpose is calling.', love: 'A tender close or transformation guided by compassion.' },
  '808': { theme: 'abundant infinite flow', meaning: 'Eight-zero-eight surrounds abundance with limitless potential — prosperity flowing in an ongoing cycle.', seeing: 'Abundance is flowing; stay balanced and open to receive.', love: 'A generous, balanced and flowing partnership.' }
};

export const ANGEL_KEYS = Object.keys(ANGEL);
