// Personal Year cycles 1-9. Drives the Personal Year pages and combines with
// each Life Path to generate the 81-cell "Life Path in a Personal Year" matrix.

export const PERSONAL_YEAR = {
  1: { theme:'new beginnings', headline:'A fresh start and new direction',
    meaning:'A Personal Year 1 opens a brand-new nine-year cycle. It is a year for fresh starts, bold decisions and planting seeds \u2014 the choices you make now set the tone for the years ahead.',
    focus:'Start things. Take initiative, back yourself, and plant the seeds you want to grow.',
    love:'A time to begin \u2014 a new relationship, or a fresh chapter and more independence within one.',
    watch:'Impatience and going it too alone; ask for help when you need it.' },
  2: { theme:'patience and relationships', headline:'A year to nurture and cooperate',
    meaning:'Personal Year 2 slows the pace after the push of Year 1. It favours patience, partnership and quiet development \u2014 things grow beneath the surface now.',
    focus:'Cooperate, build relationships, and let things develop rather than forcing them.',
    love:'Deepening bonds and partnership; sensitivity and diplomacy are rewarded.',
    watch:'Over-sensitivity and impatience with the slower pace.' },
  3: { theme:'expression and joy', headline:'A social, creative, expressive year',
    meaning:'Personal Year 3 brings lightness, creativity and connection. Doors open socially, self-expression flows, and life feels more fun \u2014 if you don\u2019t scatter your energy.',
    focus:'Create, communicate and enjoy life \u2014 but stay focused so your gifts land.',
    love:'A warm, social, romantic year; express your feelings openly.',
    watch:'Scattering energy and avoiding the serious tasks.' },
  4: { theme:'work and foundations', headline:'A year to build and get organised',
    meaning:'Personal Year 4 is a working year. It rewards discipline, structure and steady effort \u2014 the foundations you lay now make later years possible.',
    focus:'Build, organise and put in the honest work; create solid foundations.',
    love:'Stability and commitment matter; show love through reliability.',
    watch:'Burnout and rigidity \u2014 pace yourself and stay flexible.' },
  5: { theme:'change and freedom', headline:'A year of change, movement and freedom',
    meaning:'Personal Year 5 shakes things loose. Expect change, opportunity, travel and the unexpected \u2014 a year to stay adaptable and say yes to new experience.',
    focus:'Embrace change, seek variety, and stay flexible as opportunities appear.',
    love:'Excitement and freedom; new energy enters, but avoid recklessness.',
    watch:'Restlessness, overindulgence and scattering yourself too thin.' },
  6: { theme:'home and responsibility', headline:'A year centred on home, love and duty',
    meaning:'Personal Year 6 turns toward home, family and responsibility. Relationships and domestic life take centre stage, and service to others brings reward.',
    focus:'Tend to home, family and relationships; give care, and accept it too.',
    love:'A year for commitment, family and deepening love \u2014 highly relationship-focused.',
    watch:'Over-giving, worry and taking on more than your share.' },
  7: { theme:'reflection and growth', headline:'A year to go inward and grow',
    meaning:'Personal Year 7 is quiet and inward. It favours reflection, study, rest and spiritual growth over outward push \u2014 a year to understand yourself more deeply.',
    focus:'Reflect, learn and rest; trust the quiet \u2014 wisdom is building.',
    love:'A more introspective year; depth and understanding over intensity.',
    watch:'Isolation and over-thinking; stay connected to others.' },
  8: { theme:'achievement and reward', headline:'A powerful year for money and results',
    meaning:'Personal Year 8 is the harvest and power year. Effort from the cycle pays off \u2014 career, money and recognition come into focus, rewarding ambition and integrity.',
    focus:'Step into your power; pursue goals, money and recognition with integrity.',
    love:'Balance ambition with the relationship; success is sweeter shared.',
    watch:'Overwork and letting the material eclipse the personal.' },
  9: { theme:'completion and release', headline:'A year of endings and letting go',
    meaning:'Personal Year 9 closes the nine-year cycle. It is a year of completion, release and reflection \u2014 clearing out what is finished to make room for the new cycle ahead.',
    focus:'Complete, forgive and release what is done; give generously and let go.',
    love:'A year of closure or deepening; release old wounds and patterns.',
    watch:'Holding on to what needs to end; resistance to letting go.' }
};
